### PR TITLE
Log-based events

### LINKED ISSUE #283: VAI Log-based eventing
# Overview

Google has introduced Task-based logging for Vertex AI Pipelines. This can be used to replace our custom eventing components.

# Tasks

- Add docs to describe the setup of the Pub/Sub log sink that is required
- Allow configuring Pub/Sub event subscription
- Replace the existing eventing setup with the simplified solution

### PR DESCRIPTION
**Pull request by jmendesky**
Closes #283

Replaces the existing setup for VAI run completion events with log-based events directly from Vertex AI/PubSub. This simplifies the architecture as the eventsource server and reduces the amount of API calls as it no longer needs to poll the Vertex AI API for state changes. Instead, events will be emitted b u Vertex AI on pipelne run completion and the eventsource server just needs to query once and populate run events. For resiliency, the eventsource server still NACKs messages in case of errors.

## Tasks

- [x] Change event source server for VAI provider to subscribe to log-based events rather than polling for updates
- [x] Documentation updated

### CODE REVIEW

**Comment by jmendesky** [comment]
ok to test

**Comment by jmendesky** [comment]
ok to test

**Comment by grahamia** [comment]
ok to test

**Comment by grahamia** [comment]
ok to test

**Review by grahamia — APPROVED** [review]
:shipit:  🕐

**Pull request merged**
