### PR TITLE
Helm installation from published packages

### PR DESCRIPTION
**Pull request by jmendesky**
- Default Helm values to point to the package repository
- Disabled manager monitoring and eventsource server by default
- Provide basic installation example
- Project root target to generate the website

### CODE REVIEW

**Comment by jmendesky** [comment]
ok to test

**Comment by jmendesky** [comment]
ok to test

**Comment by paoloambrosio-skyuk** [comment]
OK to test

**Comment by paoloambrosio-skyuk** [comment]
OK to test

**Comment by paoloambrosio-skyuk** [comment]
OK to test

**Comment by jmendesky** [comment]
ok to test

**Comment by jmendesky** [comment]
ok to test

**Review by paoloambrosio-skyuk — APPROVED** [review]

**Comment by jmendesky** [comment]
ok to test

**Comment by jmendesky** [comment]
ok to test

**Comment by jmendesky** [comment]
ok to test

**Comment by jmendesky** [comment]
ok to test

**Comment by jmendesky** [comment]
ok to test

**Comment by jmendesky** [comment]
ok to test

**Comment by jmendesky** [comment]
ok to test

**Comment by jmendesky** [comment]
ok to test

**Comment by jmendesky** [comment]
ok to test

**Comment by jmendesky** [comment]
ok to test

**Comment by jmendesky** [comment]
ok to test

**Comment by jmendesky** [comment]
ok to test

**Pull request merged**
