### PR TITLE
Validate Set structures

### LINKED ISSUE #241: Validate Set structures in RunConfiguration CRDs
Set structures in CRDs currently are convention-only because the corresponding [kubebuilder annotation](https://book.kubebuilder.io/reference/markers/crd-validation.html) is not allowed.

The affected fields are:
- `spec.triggers.schedules`
- `spec.triggers.onChange`

### PR DESCRIPTION
**Pull request by jmendesky**
Closes #241

### CODE REVIEW

**Comment by jmendesky** [comment]
ok to test

**Comment by jmendesky** [comment]
ok to test

**Comment by jmendesky** [comment]
ok to test

**Review by paoloambrosio-skyuk — APPROVED** [review]

**Comment by jmendesky** [comment]
ok to test

**Comment by jmendesky** [comment]
ok to test

**Pull request merged**
